apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # labels of deployemnt resource
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
  # As we have many pods ,we should give what labels the deployment to match
    matchLabels:
      app: frontend
      tier: web
      project: expense
  # pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: expense
        image: jayakrishna1993/frontend:1.0.0

---

kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:     #labels are used as selectors
    app: frontend
    tier: web
    project: expense
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80   #target container port
    nodePort: 30007